import {expect,test,Page} from '@playwright/test';
async function navigate(page:Page,name:string){const menu=page.getByRole('button',{name:'Abrir menu'});if(await menu.isVisible())await menu.click();await page.getByRole('button',{name}).click()}
test('navega por URLs independentes e preserva refresh',async({page})=>{await page.goto('/');await navigate(page,'Customer 360');await expect(page).toHaveURL(/customer-360$/);await expect(page.getByRole('heading',{name:'Customer 360'})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Customer 360'})).toBeVisible();await navigate(page,'Health Score');await expect(page).toHaveURL(/health-score$/)});
test('combina filtros, pesquisa e estado vazio',async({page})=>{await page.goto('/customer-360');await page.getByLabel('Risco').selectOption('Crítico');expect(await page.locator('tbody tr').count()).toBeGreaterThan(0);await page.getByLabel('Pesquisar').fill('conta inexistente');await expect(page.getByText('Nenhuma conta corresponde aos filtros.')).toBeVisible();await expect(page.getByText('0 contas')).toBeVisible()});
test('abre modal acessível e fecha com Escape',async({page})=>{await page.goto('/customer-360');await page.getByRole('button',{name:/Abrir diagnóstico/}).first().click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await expect(page.getByRole('button',{name:'Fechar diagnóstico'})).toBeFocused();await page.keyboard.press('Escape');await expect(dialog).toBeHidden()});
test('seleciona conta específica e devolve foco ao acionador',async({page})=>{await page.goto('/customer-360');const trigger=page.getByRole('button',{name:'Abrir diagnóstico de Aurora Labs'});await trigger.click();await expect(page.getByRole('dialog').getByRole('heading',{name:'Aurora Labs'})).toBeVisible();await page.keyboard.press('Escape');await expect(trigger).toBeFocused()});
test('simulador de Health recalcula e restaura padrões',async({page})=>{await page.goto('/health-score');const slider=page.getByLabel('Peso de Adoção do produto');await slider.fill('40');await expect(page.getByText('115%',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Restaurar padrões'}).click();await expect(page.getByText('100%',{exact:true})).toBeVisible()});
test('simulador financeiro respeita extremos',async({page})=>{await page.goto('/revenue-risk');const slider=page.getByLabel('Taxa de conversão em churn');await slider.fill('100');await expect(page.getByText('R$ 0',{exact:true})).toBeVisible();await slider.fill('0');await expect(page.getByText('0%',{exact:true})).toBeVisible()});
test('mudança de peso recalcula categorias e MRR em risco',async({page})=>{await page.goto('/health-score');const before=await page.getByText(/mudam de faixa/).locator('..').innerText();const beforeRisk=await page.getByText('MRR em risco simulado').locator('..').innerText();await page.getByLabel('Peso de Adoção do produto').fill('0');const after=await page.getByText(/mudam de faixa/).locator('..').innerText();const afterRisk=await page.getByText('MRR em risco simulado').locator('..').innerText();expect(after).not.toBe(before);expect(afterRisk).not.toBe(beforeRisk)});
test('menu mobile abre, navega e fecha',async({page},testInfo)=>{test.skip(testInfo.project.name!=='mobile');await page.goto('/');const menu=page.getByRole('button',{name:'Abrir menu'});await menu.click();await expect(page.getByRole('navigation',{name:'Navegação principal'})).toBeVisible();await page.getByRole('button',{name:'Revenue Risk'}).click();await expect(page).toHaveURL(/revenue-risk$/);await expect(page.getByRole('button',{name:'Abrir menu'})).toHaveAttribute('aria-expanded','false')});
test('rota inexistente apresenta 404',async({page})=>{const response=await page.goto('/rota-inexistente');expect(response?.status()).toBe(404);await expect(page.getByText(/could not be found/i)).toBeVisible()});
test('Copilot permite editar, aceitar e rejeitar sem execução externa',async({page})=>{await page.goto('/ai-copilot');const draft=page.getByLabel('Rascunho editável');await draft.fill('Ação revisada pelo responsável.');await expect(page.getByText(/Editado — requer nova revisão/)).toBeVisible();await page.getByRole('button',{name:'Aceitar'}).click();await expect(page.getByText(/Aceito para registro manual/)).toBeVisible();await page.getByRole('button',{name:'Rejeitar'}).click();await expect(page.getByText(/Rejeitado — nenhuma ação executada/)).toBeVisible()});
