import {Account,AutomationRule,HealthKey,RevenueMovement} from './types';import {defaultWeights,healthScore,riskClass} from './rules';
export const AS_OF_DATE='2026-08-13';
const names=['Aurora Laboratórios','Nexo Digital','Prisma Nuvem','Vértice Sistemas','Lumina Tecnologia','Órbita Dados','Ponte Análises','Horizonte Software','Íris Automação','Croma Gestão','Farol Operações','Delta Perspectivas','Atlas Serviços','Movva Tecnologia','Pulso Digital','Cubo Sistemas','Trilha Laboratórios','Viva Dados','Elo Automação','Norte Nuvem','Soma Tecnologia','Base Gestão','Fluxo Sistemas','Lume Análises','Via Digital','Atria Nuvem','Núcleo Dados','Clara Sistemas','Ritmo Tecnologia','Pilar Gestão','Aster Laboratórios','Mosaico Digital','Integra Nuvem','Sinapse Dados','Vetor Gestão','Cais Tecnologia'];
const csms=['Ana Costa','Bruno Lima','Carla Nunes','Diego Alves'];const stages=['Integração inicial','Adoção','Valor','Renovação','Expansão','Recuperação'];
const isoAfter=(days:number)=>{const d=new Date(`${AS_OF_DATE}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};
function parts(i:number,adoption:number,tickets:number,severity:Account['ticketSeverity'],decision:boolean,usage:number,nps:number|null,renewalDays:number):Record<HealthKey,number>{const cohort=[-25,-10,0,10][i%4],clamp=(v:number)=>Math.max(10,Math.min(100,v+cohort));const support=95-tickets*7-(severity==='Crítica'?35:severity==='Alta'?20:0);const stakeholders=(decision?40:0)+(i%6!==0?30:0)+25;const engagement=usage+(i%3)*6-8;const value=nps===null?50:40+nps*6;const contract=55+renewalDays/8-(decision?0:15);return {adoption:clamp(adoption),engagement:clamp(engagement),value:clamp(value),support:clamp(support),stakeholders:clamp(stakeholders),contract:clamp(contract),outcome:clamp((adoption+value)/2)}}
export const accounts:Account[]=names.map((name,i)=>{const mrr=2800+((i*1379)%19200),contracted=25+((i*23)%210),usage=Math.min(96,45+((i*17)%52)),active=Math.round(contracted*usage/100),tickets=i%7,severity:Account['ticketSeverity']=i%11===0?'Crítica':i%5===0?'Alta':i%3===0?'Média':'Baixa',decision=i%7!==0,renewalDays=15+((i*29)%340),nps=i===9?null:(i*3)%11,adoption=Math.min(98,35+((i*19)%64)),components=parts(i,adoption,tickets,severity,decision,usage,nps,renewalDays),health=healthScore(components,defaultWeights),potential=health>=70?Math.round(mrr*(.15+(i%4)*.08)):0;return {id:`ACC-${String(i+1).padStart(3,'0')}`,name,segment:i%5===0?'Enterprise':i%2===0?'Mid-market':'SMB',plan:i%4===0?'Scale':i%3===0?'Growth':'Core',mrr,arr:mrr*12,startDate:`202${i%5}-0${(i%9)+1}-15`,renewalDate:isoAfter(renewalDays),contractedUsers:contracted,activeUsers:active,usage,adoption,adoptionTrend:(i%5===0?-24:-8)+(i%4)*9,tickets,ticketSeverity:severity,resolutionHours:8+(i*7)%70,nps,lastContactDays:5+(i*17)%120,userRelation:true,managerRelation:i%6!==0,decisionMakerRelation:decision,components,health,risk:riskClass(health),expansionPotential:potential,expansionInProgress:i===17,stage:stages[i%stages.length],csm:csms[i%csms.length],nextAction:i%9===0?null:health<60?'Plano de recuperação':'Revisar resultados',actionSla:i%9===0?null:`${1+i%8} dias`,confidence:nps===null?55:decision?88:70,history:[health+8,health+5,health+2,health].map(v=>Math.max(10,Math.min(98,v)))};});
export const revenueMovements:RevenueMovement[]=accounts.map((a,i)=>({accountId:a.id,openingMrr:Math.round(a.mrr*(.96+(i%5)*.01)),churn:i%17===0?Math.round(a.mrr*.35):0,contraction:i%13===0?Math.round(a.mrr*.08):0,expansion:i%7===0?Math.round(a.mrr*.12):0,reactivation:i===22?900:0}));
export const automationRules:AutomationRule[]=[{id:'critical_recovery',name:'Recuperação crítica',status:'Em teste',description:'Índice de Saúde < 40 e renovação < 60 dias',owner:'Operações de CS',sla:'1 dia',channel:'Fila interna',successMetric:'Plano validado no SLA'},{id:'adoption_drop',name:'Queda de adoção',status:'Em teste',description:'Queda > 20% em 14 dias',owner:'CSM',sla:'2 dias',channel:'Fila interna',successMetric:'Validação registrada'},{id:'usage_limit',name:'Uso no limite',status:'Simulada',description:'Saudável e uso > 85%',owner:'CSM',sla:'5 dias',channel:'Fila de expansão',successMetric:'Demanda validada'},{id:'missing_action',name:'Campo crítico ausente',status:'Em teste',description:'Ação ou SLA ausente',owner:'Responsável pelos dados',sla:'1 dia',channel:'Qualidade',successMetric:'Campo corrigido'},{id:'sponsor_absent',name:'Patrocinador executivo ausente',status:'Simulada',description:'Sem decisor e sem contato há > 90 dias',owner:'CSM',sla:'10 dias',channel:'Fila executiva',successMetric:'Contato executivo realizado'}];
export const healthMeta=[['adoption','Adoção do produto','Telemetria'],['engagement','Engajamento','CRM'],['value','Percepção de valor','Pesquisa'],['support','Saúde do suporte','Central de atendimento'],['stakeholders','Partes interessadas','CRM'],['contract','Risco contratual','Faturamento'],['outcome','Resultado de negócio','Reunião de resultados']] as const;
export const auditFixtures={missingSurvey:{...accounts[9],id:'FIX-MISSING-NPS',name:'Conta sem pesquisa',nps:null,confidence:55},contradictorySignals:{...accounts[4],id:'FIX-CONTRADICTORY',name:'Conta com sinais contraditórios',adoption:94,usage:92,nps:9,tickets:4,ticketSeverity:'Crítica' as const,decisionMakerRelation:false,expansionPotential:9000},silentRisk:{...accounts[8],id:'FIX-SILENT-RISK',name:'Conta com risco silencioso',nps:9,tickets:0,ticketSeverity:'Baixa' as const,adoptionTrend:-28,decisionMakerRelation:false,lastContactDays:108},boundaryScore:{...accounts[12],id:'FIX-BOUNDARY',name:'Conta no limite',health:60,risk:'Atenção' as const},falsePositiveCandidate:{...accounts[20],id:'FIX-FALSE-POSITIVE',name:'Candidato a falso positivo',health:82,risk:'Saudável' as const,ticketSeverity:'Crítica' as const,decisionMakerRelation:false}} satisfies Record<string,Account>;
