import {Account,AutomationRule,HealthKey,HealthWeights,RevenueMovement,Risk} from './types';
export const defaultWeights:HealthWeights={adoption:25,engagement:15,value:15,support:10,stakeholders:15,contract:10,outcome:10};
const keys:HealthKey[]=['adoption','engagement','value','support','stakeholders','contract','outcome'];
const finite=(v:number)=>Number.isFinite(v);
export function healthScore(c:Record<HealthKey,number>,w:HealthWeights=defaultWeights){const values=keys.map(k=>c[k]),weights=keys.map(k=>w[k]);if(values.some(v=>!finite(v)||v<0||v>100))throw new RangeError('Componentes devem estar entre 0 e 100.');if(weights.some(v=>!finite(v)||v<0))throw new RangeError('Pesos devem ser finitos e não negativos.');const total=weights.reduce((a,b)=>a+b,0);if(total<=0)throw new RangeError('A soma dos pesos deve ser maior que zero.');return Math.round(keys.reduce((s,k)=>s+c[k]*w[k],0)/total)}
export function riskClass(score:number):Risk{if(!finite(score)||score<0||score>100)throw new RangeError('Score deve estar entre 0 e 100.');return score<40?'Crítico':score<60?'Risco':score<80?'Atenção':'Saudável'}
export function mrrAtRisk(accounts:Account[]){return accounts.filter(a=>a.health<60).reduce((s,a)=>s+a.mrr,0)}
export function retention(m:RevenueMovement[]){const opening=m.reduce((s,x)=>s+x.openingMrr,0);if(opening<=0)throw new RangeError('Base inicial deve ser positiva.');const churn=m.reduce((s,x)=>s+x.churn,0),contraction=m.reduce((s,x)=>s+x.contraction,0),expansion=m.reduce((s,x)=>s+x.expansion,0),reactivation=m.reduce((s,x)=>s+x.reactivation,0);return {opening,churn,contraction,expansion,reactivation,grr:(opening-churn-contraction)/opening*100,nrr:(opening-churn-contraction+expansion+reactivation)/opening*100}}
export function scenario(accounts:Account[],rate:number){if(!finite(rate)||rate<0||rate>1)throw new RangeError('Taxa deve estar entre 0 e 1.');const exposed=mrrAtRisk(accounts)*12;const churn=Math.round(exposed*rate);return {exposed,churn,notConverted:exposed-churn,accountsToRecover:Math.ceil(accounts.filter(a=>a.health<60).length*(1-rate))}}
export function expansionEligible(a:Account){return a.health>=70&&a.confidence>=70&&a.nps!==null&&a.nps>=7&&a.expansionPotential>0&&a.contractedUsers>0&&(a.usage>=80||a.activeUsers/a.contractedUsers>=.8)&&a.decisionMakerRelation&&a.ticketSeverity!=='Crítica'&&!a.expansionInProgress&&!(a.health<80&&daysUntil(a.renewalDate)<60)}
export function filterAccounts(accounts:Account[],risk='Todos',csm='Todos',segment='Todos',expansion=false){return accounts.filter(a=>(risk==='Todos'||a.risk===risk)&&(csm==='Todos'||a.csm===csm)&&(segment==='Todos'||a.segment===segment)&&(!expansion||expansionEligible(a)))}
export function daysUntil(date:string,asOf='2026-08-13'){return Math.ceil((new Date(`${date}T00:00:00Z`).getTime()-new Date(`${asOf}T00:00:00Z`).getTime())/86400000)}
export function priorityScore(a:Account){const risk=(100-a.health)*3,renewal=Math.max(0,120-daysUntil(a.renewalDate))*1.5,value=Math.min(60,a.mrr/400),trend=Math.max(0,-a.adoptionTrend)*1.2,sponsor=a.decisionMakerRelation?0:35,coverage=a.nextAction?0:25;return Math.round(risk+renewal+value+trend+sponsor+coverage)}
export function validateAccounts(accounts:Account[]){const errors:string[]=[];const ids=new Set<string>();for(const a of accounts){if(ids.has(a.id))errors.push(`${a.id}: ID duplicado`);ids.add(a.id);if(a.arr!==a.mrr*12)errors.push(`${a.id}: ARR divergente`);if(a.mrr<=0)errors.push(`${a.id}: MRR inválido`);if(a.activeUsers>a.contractedUsers||a.contractedUsers<=0)errors.push(`${a.id}: usuários inválidos`);if(a.usage<0||a.usage>100||a.health<0||a.health>100)errors.push(`${a.id}: percentual inválido`);if(new Date(a.startDate)>=new Date(a.renewalDate))errors.push(`${a.id}: datas inválidas`);if(riskClass(a.health)!==a.risk)errors.push(`${a.id}: faixa divergente`)}return errors}
export function evaluateAutomation(rule:AutomationRule,a:Account,eventId:string,seen:Set<string>){if(rule.status==='Pausada'||seen.has(`${rule.id}:${eventId}`))return {triggered:false,reason:rule.status==='Pausada'?'Regra pausada':'Evento duplicado'};let triggered=false;if(rule.id==='critical_recovery')triggered=a.health<40&&daysUntil(a.renewalDate)<60;if(rule.id==='adoption_drop')triggered=a.adoptionTrend<-20;if(rule.id==='usage_limit')triggered=a.health>=80&&a.usage>85;if(rule.id==='missing_action')triggered=!a.nextAction||!a.actionSla;if(rule.id==='sponsor_absent')triggered=!a.decisionMakerRelation&&a.lastContactDays>90;if(triggered)seen.add(`${rule.id}:${eventId}`);return {triggered,reason:triggered?'Condição satisfeita':'Condição não satisfeita'}}
